name: jobber_ME01_gme_offerte

on:
  push:
    branches:
      - main  
  schedule:
    - cron: '0 0 * * *'  

jobs:
  run-r-job:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libsasl2-dev jq libpq-dev libcurl4-openssl-dev

    - name: Install dependencies with renv
      run: |
        Rscript -e "install.packages('renv')"
        Rscript -e "renv::restore()"

    - name: Set up Git credentials for private repo access
      run: |
        git config --global url."https://${{ secrets.PAT_GITHUB }}@github.com/".insteadOf "https://github.com/"

    - name: Install `fluxer` package from GitHub
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_github('mbsenergy/fluxer', auth_token = '${{ secrets.PAT_GITHUB }}')"

    - name: Run Jobber full script
      env:
        PG_FLUX_DBNAME: ${{ secrets.PG_FLUX_DBNAME }}
        PG_FLUX_HOST: ${{ secrets.PG_FLUX_HOST }}
        PG_FLUX_PORT: ${{ secrets.PG_FLUX_PORT }}
        PG_FLUX_USER: ${{ secrets.PG_FLUX_USER }}
        PG_FLUX_PSW: ${{ secrets.PG_FLUX_PSW }}
      run: |
        Rscript -e 'source("RScripts/00_jobber.R")'